### ISSUE TITLE
stock detail #1

### ISSUE THREAD

**Issue by saurabh1110** [thenitish23121991/stockal#3]
In mobile view on clicking "Predictive Analysis" it's changes the "Social Media Pulse" section structure. Please check screenshot.
![screen shot 2016-04-18 at 3 19 27 pm](https://cloud.githubusercontent.com/assets/18459858/14600450/430baef0-057a-11e6-8f11-07e52c8c1581.png)

**Comment by saurabh1110** [comment]
Not fixed yet, getting same result

**Comment by nitsh7084** [comment]
It's fixed now!

**Comment by saurabh1110** [comment]
thanks
